### ISSUE TITLE
Some emoji return undefined

### ISSUE THREAD

**Issue by kentcdodds** [ritz078/emoji-assistant#10]
I have the AI thing disabled if that makes any difference, but I'm seeing this:

![shrug](https://user-images.githubusercontent.com/1500684/28936407-e5d16bd2-7844-11e7-8d6f-757353bd5188.gif)

Not sure what other emoji are having the same issue.

**Comment by kentcdodds** [comment]
You're awesome! Thank you so much!

**Comment by ritz078** [comment]
You are most welcome. 😃
