### ISSUE TITLE
Migrate extension from a background page to an event page

### ISSUE THREAD

**Issue by yeskunall** [ritz078/emoji-assistant#3]
First and foremost: **_love_** the idea behind the extension.

With that being said: is it possible to change the extension from running constantly in the background to only run when needed? The extension in its current state takes a little over **10K** of memory on my machine running `Windows 8.1`.

**Comment by ritz078** [comment]
currently, there are some events that can only run in the background like `chrome.tabs.onActivated` as `chrome.tabs` isn't accessible in the content script but I will definitely look if there is a solution without that.

Edit: Sorry you mentioned event page. I will try .

**Comment by ritz078** [comment]
Thanks. It's done in v0.2.2
